// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: errors/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode định nghĩa các mã lỗi chuẩn trong hệ thống
type ErrorCode int32

const (
	// General errors (0-999)
	ErrorCode_UNSPECIFIED         ErrorCode = 0
	ErrorCode_INTERNAL            ErrorCode = 1
	ErrorCode_INVALID_ARGUMENT    ErrorCode = 2
	ErrorCode_NOT_FOUND           ErrorCode = 3
	ErrorCode_ALREADY_EXISTS      ErrorCode = 4
	ErrorCode_PERMISSION_DENIED   ErrorCode = 5
	ErrorCode_UNAUTHENTICATED     ErrorCode = 6
	ErrorCode_RESOURCE_EXHAUSTED  ErrorCode = 7
	ErrorCode_FAILED_PRECONDITION ErrorCode = 8
	ErrorCode_ABORTED             ErrorCode = 9
	ErrorCode_OUT_OF_RANGE        ErrorCode = 10
	ErrorCode_UNIMPLEMENTED       ErrorCode = 11
	ErrorCode_UNAVAILABLE         ErrorCode = 12
	ErrorCode_DEADLINE_EXCEEDED   ErrorCode = 13
	ErrorCode_FORBIDDEN           ErrorCode = 14 // Forbidden error
	ErrorCode_HTTP_OK             ErrorCode = 15 // HTTP OK response
	// Authentication errors (1000-1999)
	ErrorCode_AUTH_INVALID_TOKEN         ErrorCode = 1000
	ErrorCode_AUTH_TOKEN_EXPIRED         ErrorCode = 1001
	ErrorCode_AUTH_INVALID_CREDENTIALS   ErrorCode = 1002
	ErrorCode_AUTH_USER_NOT_FOUND        ErrorCode = 1003
	ErrorCode_AUTH_USER_ALREADY_EXISTS   ErrorCode = 1004
	ErrorCode_AUTH_INVALID_REFRESH_TOKEN ErrorCode = 1005
	ErrorCode_AUTH_OAUTH_FAILED          ErrorCode = 1006
	// Room management errors (2000-2999)
	ErrorCode_ROOM_NOT_FOUND       ErrorCode = 2000
	ErrorCode_ROOM_ALREADY_EXISTS  ErrorCode = 2001
	ErrorCode_ROOM_FULL            ErrorCode = 2002
	ErrorCode_ROOM_CLOSED          ErrorCode = 2003
	ErrorCode_ROOM_ACCESS_DENIED   ErrorCode = 2004
	ErrorCode_ROOM_CREATION_FAILED ErrorCode = 2005
	ErrorCode_ROOM_INVALID_STATE   ErrorCode = 2006
	// Recording errors (3000-3999)
	ErrorCode_RECORDING_NOT_FOUND       ErrorCode = 3000
	ErrorCode_RECORDING_ALREADY_EXISTS  ErrorCode = 3001
	ErrorCode_RECORDING_START_FAILED    ErrorCode = 3002
	ErrorCode_RECORDING_STOP_FAILED     ErrorCode = 3003
	ErrorCode_RECORDING_UPLOAD_FAILED   ErrorCode = 3004
	ErrorCode_RECORDING_DOWNLOAD_FAILED ErrorCode = 3005
	// AI Analysis errors (4000-4999)
	ErrorCode_AI_ANALYSIS_FAILED      ErrorCode = 4000
	ErrorCode_AI_TRANSCRIPTION_FAILED ErrorCode = 4001
	ErrorCode_AI_SUMMARY_FAILED       ErrorCode = 4002
	ErrorCode_AI_SERVICE_UNAVAILABLE  ErrorCode = 4003
	ErrorCode_AI_QUOTA_EXCEEDED       ErrorCode = 4004
	// Report errors (5000-5999)
	ErrorCode_REPORT_NOT_FOUND         ErrorCode = 5000
	ErrorCode_REPORT_GENERATION_FAILED ErrorCode = 5001
	ErrorCode_REPORT_EXPORT_FAILED     ErrorCode = 5002
	// Integration errors (6000-6999)
	ErrorCode_INTEGRATION_LIVEKIT_FAILED      ErrorCode = 6000
	ErrorCode_INTEGRATION_STORAGE_FAILED      ErrorCode = 6001
	ErrorCode_INTEGRATION_CACHE_FAILED        ErrorCode = 6002
	ErrorCode_INTEGRATION_EXTERNAL_API_FAILED ErrorCode = 6003
	// Database errors (7000-7999)
	ErrorCode_DB_CONNECTION_FAILED    ErrorCode = 7000
	ErrorCode_DB_QUERY_FAILED         ErrorCode = 7001
	ErrorCode_DB_TRANSACTION_FAILED   ErrorCode = 7002
	ErrorCode_DB_CONSTRAINT_VIOLATION ErrorCode = 7003
	// Custom errors for AI Controller and Webhook
	ErrorCode_INVALID_PAYLOAD       ErrorCode = 8000 // Payload không hợp lệ
	ErrorCode_MISSING_RECORDING_URL ErrorCode = 8001 // Thiếu URL ghi âm
	ErrorCode_PROCESSING_FAILED     ErrorCode = 8002 // Xử lý thất bại
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "UNSPECIFIED",
		1:    "INTERNAL",
		2:    "INVALID_ARGUMENT",
		3:    "NOT_FOUND",
		4:    "ALREADY_EXISTS",
		5:    "PERMISSION_DENIED",
		6:    "UNAUTHENTICATED",
		7:    "RESOURCE_EXHAUSTED",
		8:    "FAILED_PRECONDITION",
		9:    "ABORTED",
		10:   "OUT_OF_RANGE",
		11:   "UNIMPLEMENTED",
		12:   "UNAVAILABLE",
		13:   "DEADLINE_EXCEEDED",
		14:   "FORBIDDEN",
		15:   "HTTP_OK",
		1000: "AUTH_INVALID_TOKEN",
		1001: "AUTH_TOKEN_EXPIRED",
		1002: "AUTH_INVALID_CREDENTIALS",
		1003: "AUTH_USER_NOT_FOUND",
		1004: "AUTH_USER_ALREADY_EXISTS",
		1005: "AUTH_INVALID_REFRESH_TOKEN",
		1006: "AUTH_OAUTH_FAILED",
		2000: "ROOM_NOT_FOUND",
		2001: "ROOM_ALREADY_EXISTS",
		2002: "ROOM_FULL",
		2003: "ROOM_CLOSED",
		2004: "ROOM_ACCESS_DENIED",
		2005: "ROOM_CREATION_FAILED",
		2006: "ROOM_INVALID_STATE",
		3000: "RECORDING_NOT_FOUND",
		3001: "RECORDING_ALREADY_EXISTS",
		3002: "RECORDING_START_FAILED",
		3003: "RECORDING_STOP_FAILED",
		3004: "RECORDING_UPLOAD_FAILED",
		3005: "RECORDING_DOWNLOAD_FAILED",
		4000: "AI_ANALYSIS_FAILED",
		4001: "AI_TRANSCRIPTION_FAILED",
		4002: "AI_SUMMARY_FAILED",
		4003: "AI_SERVICE_UNAVAILABLE",
		4004: "AI_QUOTA_EXCEEDED",
		5000: "REPORT_NOT_FOUND",
		5001: "REPORT_GENERATION_FAILED",
		5002: "REPORT_EXPORT_FAILED",
		6000: "INTEGRATION_LIVEKIT_FAILED",
		6001: "INTEGRATION_STORAGE_FAILED",
		6002: "INTEGRATION_CACHE_FAILED",
		6003: "INTEGRATION_EXTERNAL_API_FAILED",
		7000: "DB_CONNECTION_FAILED",
		7001: "DB_QUERY_FAILED",
		7002: "DB_TRANSACTION_FAILED",
		7003: "DB_CONSTRAINT_VIOLATION",
		8000: "INVALID_PAYLOAD",
		8001: "MISSING_RECORDING_URL",
		8002: "PROCESSING_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"UNSPECIFIED":                     0,
		"INTERNAL":                        1,
		"INVALID_ARGUMENT":                2,
		"NOT_FOUND":                       3,
		"ALREADY_EXISTS":                  4,
		"PERMISSION_DENIED":               5,
		"UNAUTHENTICATED":                 6,
		"RESOURCE_EXHAUSTED":              7,
		"FAILED_PRECONDITION":             8,
		"ABORTED":                         9,
		"OUT_OF_RANGE":                    10,
		"UNIMPLEMENTED":                   11,
		"UNAVAILABLE":                     12,
		"DEADLINE_EXCEEDED":               13,
		"FORBIDDEN":                       14,
		"HTTP_OK":                         15,
		"AUTH_INVALID_TOKEN":              1000,
		"AUTH_TOKEN_EXPIRED":              1001,
		"AUTH_INVALID_CREDENTIALS":        1002,
		"AUTH_USER_NOT_FOUND":             1003,
		"AUTH_USER_ALREADY_EXISTS":        1004,
		"AUTH_INVALID_REFRESH_TOKEN":      1005,
		"AUTH_OAUTH_FAILED":               1006,
		"ROOM_NOT_FOUND":                  2000,
		"ROOM_ALREADY_EXISTS":             2001,
		"ROOM_FULL":                       2002,
		"ROOM_CLOSED":                     2003,
		"ROOM_ACCESS_DENIED":              2004,
		"ROOM_CREATION_FAILED":            2005,
		"ROOM_INVALID_STATE":              2006,
		"RECORDING_NOT_FOUND":             3000,
		"RECORDING_ALREADY_EXISTS":        3001,
		"RECORDING_START_FAILED":          3002,
		"RECORDING_STOP_FAILED":           3003,
		"RECORDING_UPLOAD_FAILED":         3004,
		"RECORDING_DOWNLOAD_FAILED":       3005,
		"AI_ANALYSIS_FAILED":              4000,
		"AI_TRANSCRIPTION_FAILED":         4001,
		"AI_SUMMARY_FAILED":               4002,
		"AI_SERVICE_UNAVAILABLE":          4003,
		"AI_QUOTA_EXCEEDED":               4004,
		"REPORT_NOT_FOUND":                5000,
		"REPORT_GENERATION_FAILED":        5001,
		"REPORT_EXPORT_FAILED":            5002,
		"INTEGRATION_LIVEKIT_FAILED":      6000,
		"INTEGRATION_STORAGE_FAILED":      6001,
		"INTEGRATION_CACHE_FAILED":        6002,
		"INTEGRATION_EXTERNAL_API_FAILED": 6003,
		"DB_CONNECTION_FAILED":            7000,
		"DB_QUERY_FAILED":                 7001,
		"DB_TRANSACTION_FAILED":           7002,
		"DB_CONSTRAINT_VIOLATION":         7003,
		"INVALID_PAYLOAD":                 8000,
		"MISSING_RECORDING_URL":           8001,
		"PROCESSING_FAILED":               8002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_errors_proto protoreflect.FileDescriptor

const file_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x13errors/errors.proto\x12\x06errors*\xd8\n" +
	"\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x04\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x05\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x06\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\a\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\b\x12\v\n" +
	"\aABORTED\x10\t\x12\x10\n" +
	"\fOUT_OF_RANGE\x10\n" +
	"\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\v\x12\x0f\n" +
	"\vUNAVAILABLE\x10\f\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\r\x12\r\n" +
	"\tFORBIDDEN\x10\x0e\x12\v\n" +
	"\aHTTP_OK\x10\x0f\x12\x17\n" +
	"\x12AUTH_INVALID_TOKEN\x10\xe8\a\x12\x17\n" +
	"\x12AUTH_TOKEN_EXPIRED\x10\xe9\a\x12\x1d\n" +
	"\x18AUTH_INVALID_CREDENTIALS\x10\xea\a\x12\x18\n" +
	"\x13AUTH_USER_NOT_FOUND\x10\xeb\a\x12\x1d\n" +
	"\x18AUTH_USER_ALREADY_EXISTS\x10\xec\a\x12\x1f\n" +
	"\x1aAUTH_INVALID_REFRESH_TOKEN\x10\xed\a\x12\x16\n" +
	"\x11AUTH_OAUTH_FAILED\x10\xee\a\x12\x13\n" +
	"\x0eROOM_NOT_FOUND\x10\xd0\x0f\x12\x18\n" +
	"\x13ROOM_ALREADY_EXISTS\x10\xd1\x0f\x12\x0e\n" +
	"\tROOM_FULL\x10\xd2\x0f\x12\x10\n" +
	"\vROOM_CLOSED\x10\xd3\x0f\x12\x17\n" +
	"\x12ROOM_ACCESS_DENIED\x10\xd4\x0f\x12\x19\n" +
	"\x14ROOM_CREATION_FAILED\x10\xd5\x0f\x12\x17\n" +
	"\x12ROOM_INVALID_STATE\x10\xd6\x0f\x12\x18\n" +
	"\x13RECORDING_NOT_FOUND\x10\xb8\x17\x12\x1d\n" +
	"\x18RECORDING_ALREADY_EXISTS\x10\xb9\x17\x12\x1b\n" +
	"\x16RECORDING_START_FAILED\x10\xba\x17\x12\x1a\n" +
	"\x15RECORDING_STOP_FAILED\x10\xbb\x17\x12\x1c\n" +
	"\x17RECORDING_UPLOAD_FAILED\x10\xbc\x17\x12\x1e\n" +
	"\x19RECORDING_DOWNLOAD_FAILED\x10\xbd\x17\x12\x17\n" +
	"\x12AI_ANALYSIS_FAILED\x10\xa0\x1f\x12\x1c\n" +
	"\x17AI_TRANSCRIPTION_FAILED\x10\xa1\x1f\x12\x16\n" +
	"\x11AI_SUMMARY_FAILED\x10\xa2\x1f\x12\x1b\n" +
	"\x16AI_SERVICE_UNAVAILABLE\x10\xa3\x1f\x12\x16\n" +
	"\x11AI_QUOTA_EXCEEDED\x10\xa4\x1f\x12\x15\n" +
	"\x10REPORT_NOT_FOUND\x10\x88'\x12\x1d\n" +
	"\x18REPORT_GENERATION_FAILED\x10\x89'\x12\x19\n" +
	"\x14REPORT_EXPORT_FAILED\x10\x8a'\x12\x1f\n" +
	"\x1aINTEGRATION_LIVEKIT_FAILED\x10\xf0.\x12\x1f\n" +
	"\x1aINTEGRATION_STORAGE_FAILED\x10\xf1.\x12\x1d\n" +
	"\x18INTEGRATION_CACHE_FAILED\x10\xf2.\x12$\n" +
	"\x1fINTEGRATION_EXTERNAL_API_FAILED\x10\xf3.\x12\x19\n" +
	"\x14DB_CONNECTION_FAILED\x10\xd86\x12\x14\n" +
	"\x0fDB_QUERY_FAILED\x10\xd96\x12\x1a\n" +
	"\x15DB_TRANSACTION_FAILED\x10\xda6\x12\x1c\n" +
	"\x17DB_CONSTRAINT_VIOLATION\x10\xdb6\x12\x14\n" +
	"\x0fINVALID_PAYLOAD\x10\xc0>\x12\x1a\n" +
	"\x15MISSING_RECORDING_URL\x10\xc1>\x12\x16\n" +
	"\x11PROCESSING_FAILED\x10\xc2>B2Z0github.com/johnquangdev/meeting-assistant/errorsb\x06proto3"

var (
	file_errors_errors_proto_rawDescOnce sync.Once
	file_errors_errors_proto_rawDescData []byte
)

func file_errors_errors_proto_rawDescGZIP() []byte {
	file_errors_errors_proto_rawDescOnce.Do(func() {
		file_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_errors_proto_rawDesc), len(file_errors_errors_proto_rawDesc)))
	})
	return file_errors_errors_proto_rawDescData
}

var file_errors_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_errors_proto_goTypes = []any{
	(ErrorCode)(0), // 0: errors.ErrorCode
}
var file_errors_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_errors_proto_init() }
func file_errors_errors_proto_init() {
	if File_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_errors_proto_rawDesc), len(file_errors_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_errors_proto_goTypes,
		DependencyIndexes: file_errors_errors_proto_depIdxs,
		EnumInfos:         file_errors_errors_proto_enumTypes,
	}.Build()
	File_errors_errors_proto = out.File
	file_errors_errors_proto_goTypes = nil
	file_errors_errors_proto_depIdxs = nil
}
