package errors

// ErrorCode định nghĩa kiểu cho mã lỗi
type ErrorCode int32

const (
	// General errors (0-999)
	ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ERROR_CODE_INTERNAL            ErrorCode = 1
	ERROR_CODE_INVALID_ARGUMENT    ErrorCode = 2
	ERROR_CODE_NOT_FOUND           ErrorCode = 3
	ERROR_CODE_ALREADY_EXISTS      ErrorCode = 4
	ERROR_CODE_PERMISSION_DENIED   ErrorCode = 5
	ERROR_CODE_UNAUTHENTICATED     ErrorCode = 6
	ERROR_CODE_RESOURCE_EXHAUSTED  ErrorCode = 7
	ERROR_CODE_FAILED_PRECONDITION ErrorCode = 8
	ERROR_CODE_ABORTED             ErrorCode = 9
	ERROR_CODE_OUT_OF_RANGE        ErrorCode = 10
	ERROR_CODE_UNIMPLEMENTED       ErrorCode = 11
	ERROR_CODE_UNAVAILABLE         ErrorCode = 12
	ERROR_CODE_DEADLINE_EXCEEDED   ErrorCode = 13

	// Authentication errors (1000-1999)
	ERROR_CODE_AUTH_INVALID_TOKEN         ErrorCode = 1000
	ERROR_CODE_AUTH_TOKEN_EXPIRED         ErrorCode = 1001
	ERROR_CODE_AUTH_INVALID_CREDENTIALS   ErrorCode = 1002
	ERROR_CODE_AUTH_USER_NOT_FOUND        ErrorCode = 1003
	ERROR_CODE_AUTH_USER_ALREADY_EXISTS   ErrorCode = 1004
	ERROR_CODE_AUTH_INVALID_REFRESH_TOKEN ErrorCode = 1005
	ERROR_CODE_AUTH_OAUTH_FAILED          ErrorCode = 1006

	// Room management errors (2000-2999)
	ERROR_CODE_ROOM_NOT_FOUND       ErrorCode = 2000
	ERROR_CODE_ROOM_ALREADY_EXISTS  ErrorCode = 2001
	ERROR_CODE_ROOM_FULL            ErrorCode = 2002
	ERROR_CODE_ROOM_CLOSED          ErrorCode = 2003
	ERROR_CODE_ROOM_ACCESS_DENIED   ErrorCode = 2004
	ERROR_CODE_ROOM_CREATION_FAILED ErrorCode = 2005
	ERROR_CODE_ROOM_INVALID_STATE   ErrorCode = 2006

	// Recording errors (3000-3999)
	ERROR_CODE_RECORDING_NOT_FOUND       ErrorCode = 3000
	ERROR_CODE_RECORDING_ALREADY_EXISTS  ErrorCode = 3001
	ERROR_CODE_RECORDING_START_FAILED    ErrorCode = 3002
	ERROR_CODE_RECORDING_STOP_FAILED     ErrorCode = 3003
	ERROR_CODE_RECORDING_UPLOAD_FAILED   ErrorCode = 3004
	ERROR_CODE_RECORDING_DOWNLOAD_FAILED ErrorCode = 3005

	// AI Analysis errors (4000-4999)
	ERROR_CODE_AI_ANALYSIS_FAILED      ErrorCode = 4000
	ERROR_CODE_AI_TRANSCRIPTION_FAILED ErrorCode = 4001
	ERROR_CODE_AI_SUMMARY_FAILED       ErrorCode = 4002
	ERROR_CODE_AI_SERVICE_UNAVAILABLE  ErrorCode = 4003
	ERROR_CODE_AI_QUOTA_EXCEEDED       ErrorCode = 4004

	// Report errors (5000-5999)
	ERROR_CODE_REPORT_NOT_FOUND         ErrorCode = 5000
	ERROR_CODE_REPORT_GENERATION_FAILED ErrorCode = 5001
	ERROR_CODE_REPORT_EXPORT_FAILED     ErrorCode = 5002

	// Integration errors (6000-6999)
	ERROR_CODE_INTEGRATION_LIVEKIT_FAILED      ErrorCode = 6000
	ERROR_CODE_INTEGRATION_STORAGE_FAILED      ErrorCode = 6001
	ERROR_CODE_INTEGRATION_CACHE_FAILED        ErrorCode = 6002
	ERROR_CODE_INTEGRATION_EXTERNAL_API_FAILED ErrorCode = 6003

	// Database errors (7000-7999)
	ERROR_CODE_DB_CONNECTION_FAILED    ErrorCode = 7000
	ERROR_CODE_DB_QUERY_FAILED         ErrorCode = 7001
	ERROR_CODE_DB_TRANSACTION_FAILED   ErrorCode = 7002
	ERROR_CODE_DB_CONSTRAINT_VIOLATION ErrorCode = 7003
)

// String returns the string representation of the error code
func (c ErrorCode) String() string {
	switch c {
	// General errors
	case ERROR_CODE_UNSPECIFIED:
		return "UNSPECIFIED"
	case ERROR_CODE_INTERNAL:
		return "INTERNAL"
	case ERROR_CODE_INVALID_ARGUMENT:
		return "INVALID_ARGUMENT"
	case ERROR_CODE_NOT_FOUND:
		return "NOT_FOUND"
	case ERROR_CODE_ALREADY_EXISTS:
		return "ALREADY_EXISTS"
	case ERROR_CODE_PERMISSION_DENIED:
		return "PERMISSION_DENIED"
	case ERROR_CODE_UNAUTHENTICATED:
		return "UNAUTHENTICATED"
	case ERROR_CODE_RESOURCE_EXHAUSTED:
		return "RESOURCE_EXHAUSTED"
	case ERROR_CODE_FAILED_PRECONDITION:
		return "FAILED_PRECONDITION"
	case ERROR_CODE_ABORTED:
		return "ABORTED"
	case ERROR_CODE_OUT_OF_RANGE:
		return "OUT_OF_RANGE"
	case ERROR_CODE_UNIMPLEMENTED:
		return "UNIMPLEMENTED"
	case ERROR_CODE_UNAVAILABLE:
		return "UNAVAILABLE"
	case ERROR_CODE_DEADLINE_EXCEEDED:
		return "DEADLINE_EXCEEDED"

	// Authentication errors
	case ERROR_CODE_AUTH_INVALID_TOKEN:
		return "AUTH_INVALID_TOKEN"
	case ERROR_CODE_AUTH_TOKEN_EXPIRED:
		return "AUTH_TOKEN_EXPIRED"
	case ERROR_CODE_AUTH_INVALID_CREDENTIALS:
		return "AUTH_INVALID_CREDENTIALS"
	case ERROR_CODE_AUTH_USER_NOT_FOUND:
		return "AUTH_USER_NOT_FOUND"
	case ERROR_CODE_AUTH_USER_ALREADY_EXISTS:
		return "AUTH_USER_ALREADY_EXISTS"
	case ERROR_CODE_AUTH_INVALID_REFRESH_TOKEN:
		return "AUTH_INVALID_REFRESH_TOKEN"
	case ERROR_CODE_AUTH_OAUTH_FAILED:
		return "AUTH_OAUTH_FAILED"

	// Room management errors
	case ERROR_CODE_ROOM_NOT_FOUND:
		return "ROOM_NOT_FOUND"
	case ERROR_CODE_ROOM_ALREADY_EXISTS:
		return "ROOM_ALREADY_EXISTS"
	case ERROR_CODE_ROOM_FULL:
		return "ROOM_FULL"
	case ERROR_CODE_ROOM_CLOSED:
		return "ROOM_CLOSED"
	case ERROR_CODE_ROOM_ACCESS_DENIED:
		return "ROOM_ACCESS_DENIED"
	case ERROR_CODE_ROOM_CREATION_FAILED:
		return "ROOM_CREATION_FAILED"
	case ERROR_CODE_ROOM_INVALID_STATE:
		return "ROOM_INVALID_STATE"

	// Recording errors
	case ERROR_CODE_RECORDING_NOT_FOUND:
		return "RECORDING_NOT_FOUND"
	case ERROR_CODE_RECORDING_ALREADY_EXISTS:
		return "RECORDING_ALREADY_EXISTS"
	case ERROR_CODE_RECORDING_START_FAILED:
		return "RECORDING_START_FAILED"
	case ERROR_CODE_RECORDING_STOP_FAILED:
		return "RECORDING_STOP_FAILED"
	case ERROR_CODE_RECORDING_UPLOAD_FAILED:
		return "RECORDING_UPLOAD_FAILED"
	case ERROR_CODE_RECORDING_DOWNLOAD_FAILED:
		return "RECORDING_DOWNLOAD_FAILED"

	// AI Analysis errors
	case ERROR_CODE_AI_ANALYSIS_FAILED:
		return "AI_ANALYSIS_FAILED"
	case ERROR_CODE_AI_TRANSCRIPTION_FAILED:
		return "AI_TRANSCRIPTION_FAILED"
	case ERROR_CODE_AI_SUMMARY_FAILED:
		return "AI_SUMMARY_FAILED"
	case ERROR_CODE_AI_SERVICE_UNAVAILABLE:
		return "AI_SERVICE_UNAVAILABLE"
	case ERROR_CODE_AI_QUOTA_EXCEEDED:
		return "AI_QUOTA_EXCEEDED"

	// Report errors
	case ERROR_CODE_REPORT_NOT_FOUND:
		return "REPORT_NOT_FOUND"
	case ERROR_CODE_REPORT_GENERATION_FAILED:
		return "REPORT_GENERATION_FAILED"
	case ERROR_CODE_REPORT_EXPORT_FAILED:
		return "REPORT_EXPORT_FAILED"

	// Integration errors
	case ERROR_CODE_INTEGRATION_LIVEKIT_FAILED:
		return "INTEGRATION_LIVEKIT_FAILED"
	case ERROR_CODE_INTEGRATION_STORAGE_FAILED:
		return "INTEGRATION_STORAGE_FAILED"
	case ERROR_CODE_INTEGRATION_CACHE_FAILED:
		return "INTEGRATION_CACHE_FAILED"
	case ERROR_CODE_INTEGRATION_EXTERNAL_API_FAILED:
		return "INTEGRATION_EXTERNAL_API_FAILED"

	// Database errors
	case ERROR_CODE_DB_CONNECTION_FAILED:
		return "DB_CONNECTION_FAILED"
	case ERROR_CODE_DB_QUERY_FAILED:
		return "DB_QUERY_FAILED"
	case ERROR_CODE_DB_TRANSACTION_FAILED:
		return "DB_TRANSACTION_FAILED"
	case ERROR_CODE_DB_CONSTRAINT_VIOLATION:
		return "DB_CONSTRAINT_VIOLATION"

	default:
		return "UNKNOWN"
	}
}
